name: 🐛 Bug Report
description: Report an issue in Hummingbird theme. DO NOT disclose security issues here, contact security@prestashop.com instead!
type: 'Bug'
projects: [ 'PrestaShop/46', 'PrestaShop/7' ]
body:
  - type: markdown
    attributes:
      value: |
        ### ❗️ Read this before submitting your bug report:
        - **Check whether the problem might come from Hummingbird theme.** If you're unsure, go ahead and describe the issue as clearly as possible. If you know it comes from a module, please report it in that module’s repository. The community and QA team will help identify the right place if needed.
        - **Write in English.** Reports in all other languages will be closed.
        - **Provide as much detail as possible** - error logs, screenshots, your exact configuration. If the issue cannot be reproduced, it cannot be fixed.
        - **Follow the [bug report guidelines](https://devdocs.prestashop-project.org/9/contribute/contribute-reporting-issues/#best-practices-for-writing-an-issue).** This will help issue managers qualify your report faster.
        - As explained [in this page](https://www.prestashop-project.org/security/sharing-third-party-distributions/), the team behind the project only maintains distribution under the official PrestaShop or PrestaShopCorp GitHub organizations. Please mention how you installed PrestaShop. If you used a third-party distribution and experience issues not reproducible with the official version, we might redirect you to that distribution's maintainers.
        - **Avoid reporting "error 500" or "white page" errors** - this is a universal error message that does not provide enough information to qualify the issue. Enable debug mode in the Performance section of PrestaShop or manually in `/config/defines.inc.php` and try again. You should get a proper error message.
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
          required: true
        - label: I have already [searched in existing issues](https://github.com/PrestaShop/hummingbird/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug and add attachments
      description: What went wrong? If possible, add screenshots, error logs, zip used or screen recordings to help explain your problem. More information you add, The more information you give us, the better we will be able to understand and fix your problem.
    validations:
      required: true
  - type: textarea
    id: step-to-reproduce
    attributes:
      label: Steps to reproduce
      description: List the exact steps to reproduce the issue.
      placeholder: |
        1. Go to ‘…’
        2. Click on ‘…’
        3. Scroll down to ‘…’
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you expected to happen instead.
  - type: textarea
    id: actual-result
    attributes:
      label: Actual Result
      description: Explains what happens and the difference between this and the expected behavior.
  - type: input
    id: prestashop-version
    attributes:
      label: PrestaShop version where the bug happens
      description: Specify which PrestaShop versions your issue come from
      placeholder: "e.g., from 1.7.5.2 or 1.7.8.0"
    validations:
      required: true
  - type: input
    id: theme-version
    attributes:
      label: Theme version where the bug happens
      description: Specify which theme versions your issue come from
      placeholder: "e.g., 1.0.0 or 1.0.1"
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP version(s) where the bug happened
      placeholder: "e.g., 7.1 or 8.0"
  - type: input
    id: sponsor-company
    attributes:
      label: Your company or customer's name goes here (if applicable).
