
name: Build ZIP File
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Build dependencies & create artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node env
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Remove unuseful data
        run: |
          rm .git/ -rf
          rm .github/ -rf
          rm .storybook/ -rf
          rm docker/ -rf
          rm docs/ -rf
          rm node_modules/ -rf
          rm src/ -rf
          rm stories/ -rf
          rm types/ -rf
          rm vendor/ -rf
          rm webpack/ -rf
          rm .editorconfig
          rm .eslintignore
          rm .eslintrc.js
          rm .gitignore
          rm .stylelintignore
          rm .stylelintrc
          rm .aider.conf.yml
          rm .antigravityrules
          rm .cursorrules
          rm .opencoderules
          rm .windsurfrules
          rm CLAUDE.md
          rm CONTEXT.md
          rm babel.config.js
          rm jest.config.js
          rm package-lock.json
          rm package.json
          rm postcss.config.js
          rm tsconfig.json
          rm webpack.config.js

      - name: Create & Upload artifact
        uses: actions/upload-artifact@v7
        with:
            name: ${{ github.event.repository.name }}
            path: ./
