name: Build & Deploy Storybook

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    name: Build & Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build storybook
        run: npm run storybook:build
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
