name: Tests
on: [ push, pull_request ]
jobs:
  js-unit-tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    strategy:
      matrix:
        js: [ '16' ]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.js }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Node Directory
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Run tests
        run: npm ci && npm run test
        working-directory: ./
